kind: pipeline
type: docker
name: default

steps:
- name: production
  image: hackercowboy/dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: appl
    path: /appl
  commands:
  - docker build -t heroku-big-files-test .
  - cd /appl;docker-compose up -d
  when:
    branch:
    - main

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: appl
  host:
    path: /appl
